apiVersion: v1
kind: Pod
metadata:
  name: platform-upgrade-12-13-to-14
  namespace: hasura
spec:
  containers:
  - name: upgrade 
    image: hasura/upgrade:12-13-to-14 
    command:
    - python
    - /update-12-13-to-14.py  
  restartPolicy: Never
